syntax = "proto3";

package transaction_v_1;

option go_package = "redbank/edge/connect/gen/transaction/v1;transactionv1";

service Service {
  rpc Health(HealthRequest) returns (HealthResponse) {
  }

  rpc PostTransaction(PostTransactionRequest) returns (PostTransactionResponse) {
  }

  rpc TransferFunds(TransferFundsRequest) returns (TransferFundsResponse) {
  }

  rpc GetTransaction(GetTransactionRequest) returns (GetTransactionResponse) {
  }

  rpc ListTransactionsByAccount(ListTransactionsByAccountRequest) returns (ListTransactionsByAccountResponse) {
  }
  // @ahum: methods
}

message HealthRequest {
}

message HealthResponse {
  string message = 1;
}

message Transaction {
  string id = 1;
  string account_id = 2;
  string type = 3;
  int64 amount = 4;
  string currency = 5;
  string status = 6;
}

message PostTransactionRequest {
  string account_id = 1;
  string type = 2;
  int64 amount = 3;
  string currency = 4;
  string reference = 5;
}

message PostTransactionResponse {
  Transaction transaction = 1;
}

message TransferFundsRequest {
  string from_account_id = 1;
  string to_account_id = 2;
  int64 amount = 3;
  string currency = 4;
  string reference = 5;
}

message TransferFundsResponse {
  Transaction from_transaction = 1;
  Transaction to_transaction = 2;
}

message GetTransactionRequest {
  string id = 1;
}

message GetTransactionResponse {
  Transaction transaction = 1;
}

message ListTransactionsByAccountRequest {
  string account_id = 1;
}

message ListTransactionsByAccountResponse {
  repeated Transaction transactions = 1;
}
// @ahum: messages
